import crypto from "crypto";
import { NextRequest, NextResponse } from "next/server";

const SHOPIFY_WEBHOOK_SECRET = process.env.SHOPIFY_WEBHOOK_SECRET;

function verifyShopifyWebhook(
    rawBody: string,
    hmacHeader: string | null
): boolean {
    if (!SHOPIFY_WEBHOOK_SECRET || !hmacHeader) {
        return false;
    }

    const generatedHash = crypto
        .createHmac("sha256", SHOPIFY_WEBHOOK_SECRET)
        .update(rawBody, "utf8")
        .digest("base64");

    try {
        return crypto.timingSafeEqual(
            Buffer.from(generatedHash),
            Buffer.from(hmacHeader)
        );
    } catch {
        return false;
    }
}

export async function POST(request: NextRequest) {
    try {
        const rawBody = await request.text();

        const hmacHeader = request.headers.get(
            "x-shopify-hmac-sha256"
        );

        const isValid = verifyShopifyWebhook(
            rawBody,
            hmacHeader
        );

        if (!isValid) {
            console.error("Invalid Shopify webhook signature");

            return NextResponse.json(
                { error: "Unauthorized" },
                { status: 401 }
            );
        }

        const order = JSON.parse(rawBody);

        console.log("=================================");
        console.log("NEW SHOPIFY ORDER");
        console.log("=================================");

        console.log({
            id: order.id,
            order_number: order.order_number,
            email: order.email,
            total_price: order.total_price,
            currency: order.currency,
            financial_status: order.financial_status,
            fulfillment_status: order.fulfillment_status,
            created_at: order.created_at,
        });

        console.log("Customer:", order.customer);

        console.log("Products:");

        for (const item of order.line_items ?? []) {
            console.log({
                product_id: item.product_id,
                variant_id: item.variant_id,
                title: item.title,
                quantity: item.quantity,
                price: item.price,
            });
        }

        /*
         * NEXT STEP:
         *
         * Save the order in Supabase.
         *
         * Then we can use this information for:
         *
         * - Sales analytics
         * - AI sales attribution
         * - Customer profiles
         * - Conversion tracking
         * - AI agent performance
         * - Revenue generated by AI
         */

        return NextResponse.json({
            success: true,
            received: true,
            order_id: order.id,
            order_number: order.order_number,
        });
    } catch (error) {
        console.error("Shopify order webhook error:", error);

        return NextResponse.json(
            {
                success: false,
                error: "Webhook processing failed",
            },
            { status: 500 }
        );
    }
}